### ISSUE TITLE
Connect livereload violates the content security policy

### ISSUE THREAD

**Issue by jantimon** [intesso/connect-livereload#40]
For security reasons we are disallowing inline styles and scripts.
http://www.html5rocks.com/en/tutorials/security/content-security-policy/

As we are using the same security settings in our development environments we are running into issues when using connect-livereload as it relies on inline scripts.

Any ideas how we could handle this?

**Comment by yankee42** [comment]
As far as I can see this will break the autoconfig of the hostname: `"//' + (location.hostname || '" + hostname + "')`. Because location.hostname cannot be accessed from the server. I assumed that this is on purpose which is why I proposed a DOM manipulation variant in #58.

However after thinking about it a little more I think I can fix that. Here is the code: https://github.com/yankee42/connect-livereload/tree/directScriptSrc

**Comment by andineck** [comment]
I like the idea of the fix. In your current implementation, the option `hostname` is not working anymore, when serving the script from another host.

what about something like this:

```js
  return function livereload(req, res, next) {
    var host = opt.hostname || req.headers.host.split(':')[0];
...
```

and then pass the `host` parameter down to the `snap` and `snippet` function?

**Comment by yankee42** [comment]
Yes, could be done like it. Here is my original solution with opt.hostname support: https://github.com/yankee42/connect-livereload/tree/directScriptSrc

and here is an alternative which I think is more like what you describe:

https://github.com/yankee42/connect-livereload/tree/directScriptSrc-passHostAsParam

**Comment by andineck** [comment]
Cool, can you delete Line 19 in https://github.com/yankee42/connect-livereload/tree/directScriptSrc-passHostAsParam :

`var hostname = opt.hostname || 'localhost';`

since that's not used anymore and send a PR?

**Comment by yankee42** [comment]
I deleted line 19 and could create a PR, but I noticed that one of the tests is failing now:
```
GET /default-test respond with inserted script:
    AssertionError: 0 == true
```
I did not fully understand what this test is testing... Coulde you have a look?

**Comment by andineck** [comment]
I just cloned your implementation:
https://github.com/yankee42/connect-livereload/tree/directScriptSrc-passHostAsParam

... and ran the tests with node 0.12.0 and 0.10.35. No Errors:
  GET /default-test
    ✓ respond with inserted script 
   ...
  57 passing (522ms)

???

**Comment by yankee42** [comment]
OK... Well... I am confused... I am still running node v0.10.25. Maybe that is the problem (I am certainly no node expert). Anyway. PR created, it is #59.
