### ISSUE TITLE
Inject script also if Accept header is not correct

### ISSUE THREAD

**Issue by yan-foto** [intesso/connect-livereload#63]
Are there any possibilities to inject the script for requests with not `Accept: html` header? In other words to disable [this check](https://github.com/intesso/connect-livereload/blob/master/index.js#L75)?

And what is the exact rationale behind the `accept` function?

**Comment by shakyShane** [comment]
The check for something like `Accept: text/html` is just one attempt at verifying that the current request is HTML and can/should be overwritten. It's a simple 'filter' that will exclude things like binary files, JS, CSS etc.

> Are there any possibilities to inject the script for requests with not Accept: html header? In other words to disable this check? 

You might want to take a look at [resp-modifier](https://github.com/shakyShane/resp-modifier) instead. This module basically 'steals' all of the logic from this one with some added features (that I needed myself for [Browsersync](https://github.com/BrowserSync/browser-sync)). For example, what you're really suggesting in your op is the idea of a whitelist - where the response is overwritten regardless.

```js
var resp = require('resp-modifier');
var mw = resp({
    rules: [
         {
              match: "some string",
              replace: "some other string",
              paths: ["**/*.html"] // whitelist all html files, skips all checks
         }
    ]
});

app.use(mw)
```

**Comment by yan-foto** [comment]
@shakyShane: thanks, I appreciate your help. I came up across this module as I was trying to migrate from all the complexity of Browsersync. But it seems that the logic is the same and the underlying concept also. If I got it right the `resp-modifier` is just a middleware and does not do all the server/watch/reload magic, right?

Another thing: to see if the script can actually be injected, I would check the response delivered by the server to see if its actually HTML instead of reading the request headers. However, I might be missing something here.

And finally: I want to make use of this module in [electron](https://github.com/atom/electron) and due to a [bug](https://github.com/atom/electron/issues/2345) the request headers does not contain `Accept`. My workaround was to use a `middleware` and add `Accept` to all `*.html` requests, but I also had no success though (also not in case of Browsersync since user middlewares are run **after** `resp-modifier`).

**Comment by shakyShane** [comment]
yep, resp-modifier is just a simple middleware for modifying responses, it has no direct relationship to Browsersync

> Another thing: to see if the script can actually be injected, I would check the response delivered by the server to see if its actually HTML instead of reading the request headers. However, I might be missing something here.

Yep, we do that too - the headers check is just 'first line of defense'

> also not in case of Browsersync since user middlewares are run after resp-modifier)

You can force your middlewares to the 'top of the stack' in Browsersync quite easily

```js

var browserSync = require('browser-sync').create();

browserSync.init({
    server: './app'
}, function (err, bs) {
    bs.addMiddleware("*", function (req, res, next) {
        res.setHeader('accept', 'text/html');
        next();
    }, {override: true});
    // override ensures your middleware always runs before any internals
});
```

**Comment by yan-foto** [comment]
@shakyShane thanks for the quick Browsersync tutorial  :+1:! 

I still think that checking the headers is little bit too restrictive, what about `Accept: */*`? Or accepts with multiple values (e.g. the infamous `image/webp,*/*;q=0.8` sent with all chrome requests). Nonetheless, I must confess that I have no better solution for now! I might as well close this issue (or should it leave it open as feature request?).
