### ISSUE TITLE
Documentation for 'disableCompression' option

### ISSUE THREAD

**Issue by woodne** [intesso/connect-livereload#64]
I was perusing the code and noticed there's an option to disableCompression on request by setting `accept-encoding` to 'identity'. Is there some reason this option is not documented?

Link to option in the code:

https://github.com/intesso/connect-livereload/blob/67062e3ac55192f2c7cae42e768e6cf59d56ad52/index.js#L21

and:

https://github.com/intesso/connect-livereload/blob/67062e3ac55192f2c7cae42e768e6cf59d56ad52/index.js#L101-L103

**Comment by andineck** [comment]
There is no deeper reason for this. It was just option was added later, and forgotten to update the README. PR welcome :-)
